Fix undeclared weights_offset in ConvGeneric Intel wave matmul codegen: `weights_offset` is declared only in case of `!weights_conversion`.
Before this fix, running Gemma4 26B on Windows Panther Lake with OpenCL gets the error:
```
 error: use of undeclared identifier 'weights_offset'; did you mean 'weights_buffer'?
  weights_offset = weights_buffer +  + (0 * 1 * 1 + 0 * 1 + 0) * shared_int4_2.x * 64;
  ^~~~~~~~~~~~~~
  weights_buffer
```

PiperOrigin-RevId: 995394224